version: '3'
services:
  order-processor-service:
    build: ./order-processor-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_CONN_STR: "postgres://user:password@postgres/db?sslmode=disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"
  
  payment-service:
    build: ./payment-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"
  
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  postgres_data:
